pkgs <- pkgs <- c("askpass", "assertthat", "backports", "base64enc", "bigD", 
"bit", "bit64", "bitops", "blob", "boot", "brew", "brio", "broom", 
"broom.helpers", "bslib", "cachem", "callr", "cellranger", "cli", 
"clipr", "commonmark", "cpp11", "crayon", "credentials", "crosstalk", 
"curl", "data.table", "DBI", "dbplyr", "desc", "devtools", "diffobj", 
"downlit", "dplyr", "dtplyr", "dygraphs", "ellipsis", "evaluate", 
"extrafont", "extrafontdb", "fansi", "farver", "fastmap", "faux", 
"fivethirtyeight", "flexdashboard", "forcats", "fs", "gargle", 
"gdtools", "generics", "gert", "ggalluvial", "ggbump", "ggiraph", 
"ggmosaic", "ggplot2movies", "ggpubr", "ggrepel", "ggthemes", 
"gh", "gitcreds", "glue", "googledrive", "googlesheets4", "gt", 
"gtable", "gtsummary", "hablar", "haven", "here", "highr", "hms", 
"hrbrthemes", "htmltools", "htmlwidgets", "httr", "hunspell", 
"ids", "ini", "isoband", "janeaustenr", "janitor", "jpeg", "jquerylib", 
"juicyjuice", "kableExtra", "knitr", "labeling", "labelled", 
"later", "lifecycle", "lme4", "lubridate", "magick", "magrittr", 
"markdown", "memoise", "mime", "miniUI", "minqa", "modelr", "nloptr", 
"openssl", "packrat", "pacman", "padr", "paletteer", "palmerpenguins", 
"patchwork", "pillar", "pkgbuild", "pkgconfig", "pkgdown", "pkgload", 
"plotly", "plyr", "praise", "prettyunits", "prismatic", "productplots", 
"profvis", "progress", "ps", "purrr", "quarto", "R.cache", "R.methodsS3", 
"R.oo", "R.utils", "R6", "ragg", "rappdirs", "rcmdcheck", "RColorBrewer", 
"Rcpp", "RcppEigen", "reactable", "reactR", "readr", "readxl", 
"rematch", "rematch2", "remotes", "repr", "reprex", "reshape2", 
"rlang", "rmarkdown", "roxygen2", "rprojroot", "rsconnect", "rstatix", 
"rstudioapi", "Rttf2pt1", "rversions", "rvest", "sass", "scales", 
"selectr", "sessioninfo", "shiny", "showtext", "showtextdb", 
"skimr", "snakecase", "SnowballC", "stringi", "stringr", "styler", 
"svglite", "sys", "sysfonts", "systemfonts", "testthat", "textshaping", 
"tibble", "tidyr", "tidyselect", "tidytext", "tidyverse", "timechange", 
"tinytex", "tokenizers", "truncnorm", "tufte", "tzdb", "urlchecker", 
"usethis", "utf8", "uuid", "V8", "vctrs", "viridisLite", "vroom", 
"waldo", "webshot", "whisker", "widyr", "withr", "xfun", "xml2", 
"xopen", "xts", "zip", "zoo")
# sort(unique(pkgs)) |> dput()
install.packages(pkgs)