ds538 <- data.frame(
  Item = c(
    "US_births_1994_2003",
    "US_births_2000_2014",
    "ahca_polls",
    "airline_safety",
    "antiquities_act",
    "august_senate_polls",
    "avengers",
    "bachelorette",
    "bad_drivers",
    "bechdel",
    "biopics",
    "bob_ross",
    "cabinet_turnover",
    "cand_events_20150114",
    "cand_events_20150130",
    "cand_state_20150114",
    "cand_state_20150130",
    "candy_rankings",
    "chess_transfers",
    "classic_rock_raw_data",
    "classic_rock_song_list",
    "college_all_ages",
    "college_grad_students",
    "college_recent_grads",
    "comma_survey",
    "congress_age",
    "cousin_marriage",
    "daily_show_guests",
    "datasets_master",
    "dem_candidates",
    "democratic_bench",
    "drinks",
    "drug_use",
    "elasticity_by_district",
    "elasticity_by_state",
    "elo_blatter",
    "endorsements",
    "endorsements_2020",
    "fandango",
    "fifa_audience",
    "fight_songs",
    "flying",
    "food_world_cup",
    "forecast_results_2018",
    "foul_balls",
    "generic_polllist",
    "generic_topline",
    "google_trends",
    "governor_national_forecast",
    "governor_state_forecast",
    "hate_crimes",
    "hiphop_cand_lyrics",
    "hist_ncaa_bball_casts",
    "hist_senate_preds",
    "house_national_forecast",
    "impeachment_polls",
    "librarians",
    "love_actually_adj",
    "love_actually_appearance",
    "mad_men",
    "male_flight_attend",
    "masculinity_survey",
    "media_mentions_cable",
    "media_mentions_online",
    "mediacloud_hurricanes",
    "mediacloud_online_news",
    "mediacloud_states",
    "mediacloud_trump",
    "mlb_as_play_talent",
    "mlb_as_team_talent",
    "mueller_approval_polls",
    "murder_2015_final",
    "murder_2016_prelim",
    "nba_draft_2015",
    "nba_draymond",
    "nba_elo_latest",
    "nba_tattoos",
    "ncaa_w_bball_tourney",
    "nfl_fandom_google",
    "nfl_fandom_surveymonkey",
    "nfl_fav_team",
    "nfl_suspensions",
    "nfltix_div_avgprice",
    "nfltix_usa_avg",
    "nflwr_aging_curve",
    "nflwr_hist",
    "nutrition_pvalues",
    "partisan_lean_district",
    "partisan_lean_state",
    "police_deaths",
    "police_killings",
    "police_locals",
    "pres_2016_trail",
    "pres_commencement",
    "pulitzer",
    "riddler_castles",
    "riddler_castles2",
    "riddler_pick_lowest",
    "russia_investigation",
    "san_andreas",
    "sandy_311",
    "senate_national_forecast",
    "senate_polls",
    "senate_seat_forecast",
    "spi_global_rankings",
    "state_index",
    "state_info",
    "state_words",
    "steak_survey",
    "tarantino",
    "tennis_events_time",
    "tennis_players_time",
    "tennis_serve_time",
    "tenth_circuit",
    "trump_approval_poll",
    "trump_approval_trend",
    "trump_lawsuits",
    "trump_news",
    "trump_twitter",
    "trumpworld_issues",
    "trumpworld_polls",
    "tv_hurricanes",
    "tv_hurricanes_by_network",
    "tv_states",
    "undefeated",
    "unisex_names",
    "weather_check",
    "wwc_2019_forecasts",
    "wwc_2019_matches"
  ),
  class = c(
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame",
    "data.frame"
  ),
  dim = c(
    "3652x6",
    "5479x6",
    "15x7",
    "56x9",
    "344x9",
    "594x11",
    "173x21",
    "887x23",
    "51x8",
    "1794x15",
    "761x14",
    "403x71",
    "312x8",
    "42x8",
    "74x8",
    "25x5",
    "27x5",
    "85x13",
    "932x5",
    "37673x7",
    "2229x7",
    "173x11",
    "173x22",
    "173x21",
    "1129x13",
    "18635x13",
    "70x2",
    "2693x5",
    "148x9",
    "811x33",
    "67x3",
    "193x5",
    "17x28",
    "435x3",
    "51x2",
    "209x8",
    "109x9",
    "1002x13",
    "146x23",
    "191x5",
    "65x23",
    "1040x27",
    "1373x48",
    "1518x11",
    "906x7",
    "1981x21",
    "1447x9",
    "37x5",
    "150x11",
    "7743x10",
    "51x13",
    "377x8",
    "253x6",
    "207x5",
    "588x11",
    "388x24",
    "371x9",
    "14x15",
    "71x15",
    "248x15",
    "320x2",
    "189x12",
    "972x7",
    "954x6",
    "38x5",
    "49x2",
    "51x4",
    "51x7",
    "3930x15",
    "172x16",
    "65x12",
    "83x5",
    "79x7",
    "1090x9",
    "3009x4",
    "1230x24",
    "636x2",
    "2092x19",
    "207x9",
    "33x25",
    "32x17",
    "269x7",
    "108x3",
    "32x2",
    "24x3",
    "6496x6",
    "27716x3",
    "435x4",
    "50x3",
    "22800x7",
    "467x34",
    "75x8",
    "177x5",
    "154x8",
    "50x7",
    "1387x11",
    "932x11",
    "3660x2",
    "194x13",
    "1013x11",
    "1783x25",
    "450x11",
    "107x4",
    "28353x12",
    "576x7",
    "50x5",
    "51x4",
    "2223x9",
    "550x15",
    "1894x4",
    "205x5",
    "218x2",
    "120x7",
    "954x13",
    "4929x19",
    "1704x9",
    "57x16",
    "286x3",
    "448x3",
    "185x6",
    "32x40",
    "37x5",
    "84x6",
    "52x4",
    "2125x4",
    "919x5",
    "928x9",
    "192x21",
    "52x18"
  ),
  Title = c(
    "Some People Are Too Superstitious To Have A Baby On Friday The 13th",
    "Some People Are Too Superstitious To Have A Baby On Friday The 13th",
    "American Health Care Act Polls",
    "Should Travelers Avoid Flying Airlines That Have Had Crashes in the Past?",
    "Trump Might Be The First President To Scrap A National Monument",
    "How Much Trouble Is Ted Cruz Really In?",
    "Joining The Avengers Is As Deadly As Jumping Off A Four-Story Building",
    "Bachelorette / Bachelor",
    "Dear Mona, Which State Has The Worst Drivers?",
    "The Dollar-And-Cents Case Against Hollywood's Exclusion of Women",
    "'Straight Outta Compton' Is The Rare Biopic Not About White Dudes",
    "A Statistical Analysis of the Work of Bob Ross",
    "Two Years In, Turnover In Trump’s Cabinet Is Still Historically High",
    "Looking For Clues: Who Is Going To Run For President In 2016?",
    "Who Will Run For President: Romney Is Out",
    "Looking For Clues: Who Is Going To Run For President In 2016?",
    "Who Will Run For President: Romney Is Out",
    "Candy Power Ranking",
    "Chess Transfers",
    "Why Classic Rock Isn't What It Used To Be",
    "Why Classic Rock Isn't What It Used To Be",
    "The Economic Guide To Picking A College Major",
    "The Economic Guide To Picking A College Major",
    "The Economic Guide To Picking A College Major",
    "Elitist, Superfluous, Or Popular? We Polled Americans on the Oxford Comma",
    "Both Republicans And Democrats Have an Age Problem",
    "How Many Americans Are Married To Their Cousins?",
    "Every Guest Jon Stewart Ever Had On 'The Daily Show'",
    "Master list of all datasets",
    "Democratic Primary Candidates 2018",
    "Some Democrats Who Could Step Up If Hillary Isn't Ready For Hillary",
    "Dear Mona Followup: Where Do People Drink The Most Beer, Wine And Spirits?",
    "How Baby Boomers Get High",
    "Political Elasticity Scores",
    "Political Elasticity Scores",
    "Blatter's Reign At FIFA Hasn't Helped Soccer's Poor",
    "Pols And Polls Say The Same Thing: Jeb Bush Is A Weak Front-Runner",
    "The 2020 Endorsement Primary - Which Democratic candidates are receiving the most support from prominent members of their party?",
    "Be Suspicious Of Online Movie Ratings, Especially Fandango's",
    "How To Break FIFA",
    "Our Guide To The Exuberant Nonsense of College Fight Songs",
    "41 Percent Of Fliers Think You're Rude If You Recline Your Seat",
    "The FiveThirtyEight International Food Association's 2014 World Cup",
    "How FiveThirtyEight's 2018 Midterm Forecasts Did",
    "We Watched 906 Foul Balls To Find Out Where The Most Dangerous Ones",
    "Congress Generic Ballot Polls",
    "Congress Generic Ballot Polls",
    "The Media Really Started Paying Attention to Puerto Rico When Trump Did",
    "2018 Governors Forecast",
    "2018 Governors Forecast",
    "Higher Rates Of Hate Crimes Are Tied To Income Inequality",
    "Hip-Hop Is Turning On Donald Trump",
    "The NCAA Bracket: Checking Our Work",
    "How The FiveThirtyEight Senate Forecast Model Works",
    "2018 House Forecast",
    "Do Americans Support Impeaching Trump?",
    "Where Are America's Librarians?",
    "The Definitive Analysis Of 'Love Actually,' The Greatest Christmas Movie Of Our Time",
    "The Definitive Analysis Of 'Love Actually,' The Greatest Christmas Movie Of Our Time",
    "\"Mad Men\" Is Ending. What's Next For The Cast?",
    "Dear Mona, How Many Flight Attendants Are Men?",
    "Masculinity Survey",
    "2020 Presidential Candidates Media Mentions",
    "2020 Presidential Candidates Media Mentions",
    "The Media Really Started Paying Attention to Puerto Rico When Trump Did",
    "The Media Really Started Paying Attention to Puerto Rico When Trump Did",
    "The Media Really Started Paying Attention to Puerto Rico When Trump Did",
    "The Media Really Started Paying Attention to Puerto Rico When Trump Did",
    "The Best MLB All-Star Teams Ever",
    "The Best MLB All-Star Teams Ever",
    "Both Parties Think The Mueller Report Was Fair. They Just Completely Disagree On What It Says.",
    "A Handful Of Cities Are Driving 2016's Rise In Murder",
    "A Handful Of Cities Are Driving 2016's Rise In Murder",
    "Projecting The Top 50 Players In The 2015 NBA Draft Class",
    "A Better Way to Evaluate NBA Defense",
    "NBA Elo Ratings",
    "Accurately Counting NBA Tattoos Isn't Easy, Even If You're Up Close",
    "The Rise And Fall Of Women's NCAA Tournament Dynasties",
    "How Every NFL Team’s Fans Lean Politically",
    "How Every NFL Team’s Fans Lean Politically",
    "The Rams Are Dead To Me, So I Answered 3,352 Questions To Find A New NFL Team",
    "The NFL's Uneven History Of Punishing Domestic Violence",
    "Who Goes To Meaningless NFL Games And Why?",
    "Who Goes To Meaningless NFL Games And Why?",
    "The Football Hall Of Fame Has A Receiver Problem",
    "The Football Hall Of Fame Has A Receiver Problem",
    "You Can't Trust What You Read About Nutrition",
    "FiveThirtyEight's Partisan Lean",
    "FiveThirtyEight's Partisan Lean",
    "The Dallas Shooting Was Among The Deadliest For Police In U.S. History",
    "Where Police Have Killed Americans In 2015",
    "Most Police Don't Live In The Cities They Serve",
    "The Last 10 Weeks Of 2016 Campaign Stops In One Handy Gif",
    "Sitting Presidents Give Way More Commencement Speeches Than They Used To",
    "Do Pulitzers Help Newspapers Keep Readers?",
    "Can You Rule Riddler Nation?",
    "The Battle For Riddler Nation, Round 2",
    "Pick A Number, Any Number",
    "Russia Investigation",
    "The Rock Isn't Alone: Lots Of People Are Worried About 'The Big One'",
    "The (Very) Long Tail Of Hurricane Recovery",
    "Senate Forecast 2018",
    "Early Senate Polls Have Plenty to Tell Us About November",
    "Senate Forecast 2018",
    "Current SPI ratings and rankings for men's club teams",
    "What America’s Governors Are Talking About",
    "Information on each state",
    "What America’s Governors Are Talking About",
    "How Americans Like Their Steak",
    "A Complete Catalog Of Every Time Someone Cursed Or Bled Out In A Quentin Tarantino Movie",
    "Why Some Tennis Matches Take Forever",
    "Why Some Tennis Matches Take Forever",
    "Why Some Tennis Matches Take Forever",
    "For A Trump Nominee, Neil Gorsuch’s Record Is Surprisingly Moderate On Immigration",
    "How Popular is Donald Trump",
    "How Popular is Donald Trump",
    "Trump Lawsuits",
    "How Trump Hacked The Media",
    "The World's Favorite Donald Trump Tweets",
    "What the World Thinks of Trump",
    "What the World Thinks of Trump",
    "The Media Really Started Paying Attention to Puerto Rico When Trump Did",
    "The Media Really Started Paying Attention to Puerto Rico When Trump Did",
    "The Media Really Started Paying Attention to Puerto Rico When Trump Did",
    "Mayweather Is Defined By The Zero Next To His Name",
    "The Most Common Unisex Names In America: Is Yours One Of Them?",
    "Where People Go To Check The Weather",
    "2019 Women's World Cup Predictions",
    "2019 Women's World Cup Predictions"
  )
)
